### PR TITLE
Fix asciinema player

### LINKED ISSUE #67: Failed to play cast file on github pages
it's time for some serious debugging. 💪 

image

### PR DESCRIPTION
**Pull request by hyrodium**
This PR fixes https://github.com/AtelierArith/Replay.jl/issues/67. I also added SIXEL examples to the documentation.

### CODE REVIEW

**Comment by hyrodium** [comment]
Should we fix the formatting, or can I relax the line-length limitation in `.JuliaFormatter`?
I personally think the formatted code is hard to read.

**Before formatting**
image

**After formating**
image

**Comment by terasakisatoshi** [comment]
> After formating

（EDIT)
I personally like this result. 

It behaves the same way as [black formatter](https://github.com/psf/black).

File: docs/make.jl [hunk 1]
```diff
@@ -52,58 +45,83 @@ function generate_example_page(sections)
...
-            <script>
-                AsciinemaPlayer.create('assets/$(name).cast', document.getElementById('$(name)'), {
-                    cols: 80,
-                    rows: 24
-                });
-            </script>
-            ```
             """
+
+            if mode == :asciinema
```
Comment (terasakisatoshi) [inline docs/make.jl:50]: Are there any plans to add modes other than `:disabled` and `:asciinema` for the future?

Comment (hyrodium) [reply docs/make.jl:50]: I was thinking that `:video` (or `:mp4`) can be added in the future to record the results with Sixel.jl. (x-ref: https://github.com/AtelierArith/Replay.jl/pull/54#discussion_r1161409540)

**Comment by hyrodium** [comment]
>I personally like this result.
>
>It behaves the same way as [black formatter](https://github.com/psf/black).

Okay, I have updated `make.jl` to adapt the current format config:+1:

Btw, both [blue style](https://github.com/invenia/BlueStyle) and [sciml style](https://github.com/SciML/SciMLStyle) have 92 character line length limit, so I thought the limit is a bit short.

File: docs/make.jl (hunk 1 above)
Comment (terasakisatoshi) [reply docs/make.jl:50]: I see 🫡

File: docs/make.jl [hunk 2]
```diff
@@ -52,58 +45,167 @@ function generate_example_page(sections)
...
+                # Record the REPL output with asciinema
+                run(cmd_record)
+
+                # Add the output of the example
+                script_md *= """
+                The output will be like this:
+                ```@raw html
+                <div id="$(name)"></div>
+                <script>
+                    AsciinemaPlayer.create('../assets/$(name).cast', document.getElementById('$(name)'), {
```
Comment (terasakisatoshi) [inline docs/make.jl:65]: I understand the situation. On the `main` branch, the parameter `prettyurls` is set to `true` on GitHub Actions while `false` locally. The file named in `example/index.html` is generated on GitHub because `prettyurls` is `true`. 
In this case, files e.g., `readme.cast` is located in `../assets` directory relative to `example/index.html`.

File: docs/make.jl [hunk 3]
```diff
@@ -116,7 +218,7 @@ makedocs(;
     repo="https://github.com/AtelierArith/Replay.jl/blob/{commit}{path}#{line}",
     sitename="Replay.jl",
     format=Documenter.HTML(;
-        prettyurls=get(ENV, "CI", "false") == "true",
+        prettyurls=true,
```
Comment (terasakisatoshi) [inline docs/make.jl:221]: x-ref https://github.com/AtelierArith/Replay.jl/pull/68/files#r1174348157

**Comment by terasakisatoshi** [comment]
> Btw, both [blue style](https://github.com/invenia/BlueStyle) and [sciml style](https://github.com/SciML/SciMLStyle) have 92 character line length limit, so I thought the limit is a bit short.

Got it. I've created #69

**Comment by terasakisatoshi** [comment]
It's time to merge this #68 pull request. And then, #69 ?

**Review by terasakisatoshi — APPROVED** [review]

**Comment by terasakisatoshi** [comment]
🚀

**Comment by terasakisatoshi** [comment]
It works (on 2023-04-23)

image

**Comment by hyrodium** [comment]
But there is now a cutting-off lines problem.. (x-ref: https://github.com/AtelierArith/Replay.jl/pull/60#issuecomment-1513045362)
